FORMAT: 1A
HOST: app.idoklad.cz/api/

# iDoklad API
iDoklad API je nástroj pro online fakturaci

# Group Úvod

Úvod do API iDokladu, základní informace

# Group Quick Start

Jednoduchý příklad jak získat seznam faktur a vytvořit fakturu

# Group Authentifikace

Informace, které se tykaji přihlašování

# Group IssuedInvoices
IssuedInvoices related resources of the **iDoklad API**

## IssuedInvoices Collection [/issuedinvoices]
### List all IssuedInvoices [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a IssuedInvoices [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## IssuedInvoice [/issuedinvoices/{id}]
A single Issuedinvoice object

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a IssuedInvoice [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a IssuedInvoice [DELETE]
+ Response 204

## MyDocumentAddress [/issuedinvoice/{id}/mydocumentaddress]
Vrati fakturacni udaje odberatele pro fakturu.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the IssuedInvoice releated to DocumentAddress

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a pricelistitems [PUT]
+ Response 204

## PurchaserDocumentAddress [/issuedinvoice/{id}/purchaserdocumentaddress]
Vrati fakturacni udaje odberatele pro fakturu.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the IssuedInvoice releated to DocumentAddress

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a pricelistitems [PUT]
+ Response 204

# Group Contacts
Contacts related resources of the **iDoklad API**

## Contacts Collection [/contacts]
### List all Contact items [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park", "invoice" : {"id":51}
        }, {
          "id": 2, "title": "Pick-up posters from post-office", "invoice" : {"id":51}
        }]

### Create a Contact [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }



# Group PriceListItems
Notes related resources of the **Notes API**

## PriceListItems Collection [/pricelistitems]
### List all Price list items [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park", "invoice" : {"id":51}
        }, {
          "id": 2, "title": "Pick-up posters from post-office", "invoice" : {"id":51}
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

