FORMAT: 1A
HOST: app.idoklad.cz/api/

# iDoklad API
iDoklad API je nástroj pro online fakturaci


# Group IssuedInvoices
IssuedInvoices related resources of the **iDoklad API**

| Field  | Description | Notes |
| ------ | ----------- | ----- |
| id     | path to data files to supply the data that will be passed into templates. |
| test   | engine to be used for processing templates. Handlebars is the default. |
| ext    | extension to be used for dest files. |

## IssuedInvoices Collection [/IssuedInvoices]
### List all IssuedInvoices [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a IssuedInvoices [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204

# Group PriceListItems
Notes related resources of the **Notes API**

## PriceListItems Collection [/pricelistitems]
### List all Price list items [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park", "invoice" : {"id":51}
        }, {
          "id": 2, "title": "Pick-up posters from post-office", "invoice" : {"id":51}
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/pricelistitems/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a pricelistitems [DELETE]
+ Response 204
